/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2d3449",
        "on-surface-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#004c69",
        "on-tertiary": "#131e8c",
        "inverse-surface": "#dae2fd",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "surface": {
          DEFAULT: "#0b1326",
          soft: "var(--surface-soft)",
          elevated: "var(--surface-elevated)",
        },
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#2f3aa3",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#000767",
        "error": "#ffb4ab",
        "primary": {
          DEFAULT: "#3cddc7",
          soft: "var(--primary-soft)",
        },
        "surface-bright": "#31394d",
        "tertiary-fixed-dim": "#bdc2ff",
        "inverse-on-surface": "#283044",
        "on-primary": "#003731",
        "surface-container-low": "#131b2e",
        "on-secondary-container": "#00374d",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "background": "#0b1326",
        "tertiary-fixed": "#e0e0ff",
        "secondary-container": "#00a6e0",
        "inverse-primary": "#006b5f",
        "on-primary-fixed-variant": "#005047",
        "secondary-fixed": "#c4e7ff",
        "surface-tint": "#3cddc7",
        "primary-fixed-dim": "#3cddc7",
        "tertiary-container": "#00055c",
        "tertiary": "#bdc2ff",
        "outline": "#909097",
        "surface-container-lowest": "#060e20",
        "on-tertiary-container": "#6c77e1",
        "primary-fixed": "#62fae3",
        "primary-container": "#001c18",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "secondary-fixed-dim": "#7bd0ff",
        "surface-container-highest": "#2d3449",
        "surface-dim": "#0b1326",
        "on-secondary": "#00354a",
        "on-primary-container": "#009182",
        "outline-variant": "#45464d",
        "on-secondary-fixed": "#001e2c",
        "secondary": "#7bd0ff",
        text: {
          DEFAULT: "var(--text)",
          muted: "var(--text-muted)",
        },
        accent: "var(--accent)",
        border: "var(--border)",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        glass: "0 20px 40px rgba(2, 6, 23, 0.18)",
        card: "0 8px 30px rgba(2, 6, 23, 0.16)",
      },
      borderRadius: {
        xl2: "1.25rem",
      },
      keyframes: {
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        shimmer: "shimmer 1.6s linear infinite",
      },
    },
  },
  plugins: [],
};

